def TS_07():
    Log.Message("7. Check whether after creating a new user and for the first login user is  able to set security questions and aswers", "")
    KeywordTests.Admin_login.Run()
    Aliases.chrome.BrowserWindow.Maximize()
    Aliases.chrome.pageEdit3.textnodeUserAdministration.linkUserAdministration.Click()
    Delay(10000)
    Aliases.browser.pageEdit.linkDataCaptureId1.Click()
    Delay(10000)
    Aliases.browser.pageRevRemit2.formNewUser.textboxUserid.Click()
    LastResult = Excel.Open("C:\\Security_Testing_RR-37\\Resources\\Security_Testing_Input.xls").SheetByTitle["TS_07"].CellByName["A3"].Value
    Aliases.browser.pageRevRemit2.formNewUser.textboxUserid.SetText(LastResult)
    Aliases.chrome.pageNew.textboxUserLogin.Click()
    LastResult1 = Excel.Open("C:\\Security_Testing_RR-37\\Resources\\Security_Testing_Input.xls").SheetByTitle["TS_07"].CellByName["B3"].Value
    Aliases.chrome.pageNew.textboxUserLogin.SetText(LastResult1)
    Aliases.chrome.pageNew.passwordboxPassword.Click()
    LastResult2 = Excel.Open("C:\\Security_Testing_RR-37\\Resources\\Security_Testing_Input.xls").SheetByTitle["Sec_Input"].CellByName["C8"].Value
    Aliases.chrome.pageNew.passwordboxPassword.SetText(LastResult2)
    Aliases.chrome.pageNew.passwordboxConfirmPassword.Click()
    LastResult3 = Excel.Open("C:\\Security_Testing_RR-37\\Resources\\Security_Testing_Input.xls").SheetByTitle["Sec_Input"].CellByName["C8"].Value
    Aliases.chrome.pageNew.passwordboxConfirmPassword.SetText(LastResult3)
    Aliases.chrome.pageNew.checkboxOadmin.ClickChecked(True)
    Aliases.chrome.pageNew.checkboxUserImagePermision.ClickChecked(True)
    Aliases.chrome.pageNew.checkboxUserImage835Permision.ClickChecked(True)
    Aliases.chrome.pageNew.checkboxUserWorklistPermission.ClickChecked(True)
    Aliases.chrome.pageNew.checkboxUserCheckIndexPermission.ClickChecked(True)
    Aliases.chrome.pageNew.checkboxUserBatchStatusPermissio.ClickChecked(True)
    Aliases.chrome.pageNew.checkboxUserFile837ReportPermiss.ClickChecked(True)
    Aliases.chrome.pageNew.textboxUserEmployeeId.Click()
    Aliases.chrome.pageNew.textboxUserEmployeeId.SetText("345354")
    Aliases.chrome.pageNew.textboxUserL1Manager.Click()
    Aliases.chrome.pageNew.textboxUserL1Manager.SetText("L1")
    Aliases.chrome.pageNew.textboxUserL2Manager.Click()
    Aliases.chrome.pageNew.textboxUserL2Manager.SetText("L2")
    Aliases.chrome.pageNew.button.ClickButton()
    Aliases.chrome.pageUser.Wait()
    aqObject.CheckProperty(Aliases.browser.pageRevRemit2.FindElement("#flash_notice"), "contentText", cmpContains, "User was successfully created.", False)
    Delay(5000)
    Aliases.browser.pageEdit.imageLogout.Click()
    Aliases.chrome.pageNew2.Wait()
    Delay(5000)
    LastResult4 = Excel.Open("C:\\Security_Testing_RR-37\\Resources\\Security_Testing_Input.xls").SheetByTitle["TS_07"].CellByName["B3"].Value
    Aliases.chrome.pageNew2.formNewUser.textboxUserid.SetText(LastResult4)
    Aliases.chrome.pageNew2.formNewUser.passwordboxUserPassword.Click()
    LastResult5 = Excel.Open("C:\\Security_Testing_RR-37\\Resources\\Security_Testing_Input.xls").SheetByTitle["Sec_Input"].CellByName["C8"].Value
    Aliases.chrome.pageNew2.formNewUser.passwordboxUserPassword.SetText(LastResult5)
    Aliases.chrome.pageNew2.formNewUser.submitbuttonLogin.ClickButton()
    Aliases.chrome.pageChangePassword.Wait()
    Aliases.chrome.pageChangePassword.passwordboxPassword.Click()
    LastResult6 = Excel.Open("C:\\Security_Testing_RR-37\\Resources\\Security_Testing_Input.xls").SheetByTitle["TS_07"].CellByName["C3"].Value
    Aliases.chrome.pageChangePassword.passwordboxPassword.SetText(LastResult6)
    Aliases.chrome.pageChangePassword.passwordboxConfirmPassword.Click()
    LastResult7 = Excel.Open("C:\\Security_Testing_RR-37\\Resources\\Security_Testing_Input.xls").SheetByTitle["TS_07"].CellByName["C3"].Value
    Aliases.chrome.pageChangePassword.passwordboxConfirmPassword.SetText(LastResult7)
    Aliases.chrome.pageChangePassword.button.ClickButton()
    Aliases.chrome.pageNew2.Wait()
    Delay(5000)
    LastResult8 = Excel.Open("C:\\Security_Testing_RR-37\\Resources\\Security_Testing_Input.xls").SheetByTitle["TS_07"].CellByName["B3"].Value
    Aliases.chrome.pageNew2.formNewUser.textboxUserid.SetText(LastResult8)
    Aliases.chrome.pageNew2.formNewUser.passwordboxUserPassword.Click()
    LastResult9 = Excel.Open("C:\\Security_Testing_RR-37\\Resources\\Security_Testing_Input.xls").SheetByTitle["TS_07"].CellByName["C3"].Value
    Aliases.chrome.pageNew2.formNewUser.passwordboxUserPassword.SetText(LastResult9)
    Aliases.chrome.pageNew2.formNewUser.submitbuttonLogin.ClickButton()
    Aliases.chrome.pageEdit3.Wait()
    Aliases.chrome.pageEdit3.selectUserSecretQuestionsQn1.ClickItem("What was your high school’s mascot?")
    Aliases.chrome.pageEdit3.selectUserSecretQuestionsQn2.ClickItem("What was the name of your first pet?")
    Aliases.chrome.pageEdit3.selectUserSecretQuestionsQn3.ClickItem("In what town or city did you attend high school?")
    Aliases.chrome.pageEdit3.textboxAns1.Click()
    LastResult10 = Excel.Open("C:\\Security_Testing_RR-37\\Resources\\Security_Testing_Input.xls").SheetByTitle["TS_07"].CellByName["I3"].Value
    Aliases.chrome.pageEdit3.textboxAns1.SetText(LastResult10)
    Aliases.chrome.pageEdit3.textboxAns2.Click()
    LastResult11 = Excel.Open("C:\\Security_Testing_RR-37\\Resources\\Security_Testing_Input.xls").SheetByTitle["TS_07"].CellByName["I3"].Value
    Aliases.chrome.pageEdit3.textboxAns2.SetText(LastResult11)
    Aliases.chrome.pageEdit3.textboxAns3.Click()
    LastResult12 = Excel.Open("C:\\Security_Testing_RR-37\\Resources\\Security_Testing_Input.xls").SheetByTitle["TS_07"].CellByName["I3"].Value
    Aliases.chrome.pageEdit3.textboxAns3.SetText(LastResult12)
    Aliases.chrome.pageEdit3.button.ClickButton()
    aqObject.CheckProperty(Aliases.browser.pageRevRemit.panelFlashError, "contentText", cmpContains, "Logged in successfully.", False)
    Delay(5000)
    Aliases.browser.pageEdit.imageLogout.Click()
    Delay(10000)
    KeywordTests.Close_Browser.Run()
    Delay(10000)
