def TS_14():
    Log.Message("14.  Verify the timeout condition, after timeout user should not able to navigate through the site.", "")
    KeywordTests.Admin_login.Run()
    Delay(1209000, "Waiting for session time out")
    aqObject.CheckProperty(Aliases.browser.pageRevRemit2.panelFlashNotice, "contentText", cmpContains, "Signed out successfully.", False)
    Aliases.chrome.ToUrl(Project.Variables.URL + "/admin/batch/new_work_list")
    Delay(5000)
    aqObject.CheckProperty(Aliases.browser.pageRevRemit2.FindElement("//li[contains(text(), 'Please login to continue')]"), "contentText", cmpContains, "Please login to continue", False)
    KeywordTests.Close_Browser.Run()
    Delay(1000)
